baseline: vanilla_vae
latent_dim: 256
losses:
  types: ['loss_recon_output', 'loss_kl_divergence', 'loss_z']
  temperature: 1.0
  weight_recon_output: 0.0
  weight_kl_divergence: 0.0
  weight_z: 1.0
  weight_z_contrastive: 0.25
  weight_z_consistency: 0.5
exp_name: 'vae_contrastive_wo_recon'